language: r
cache: packages

r:
  - release

sudo: false

r_packages:
  - BayesLogit
  - coda
  - testthat
  - R.rsp
  - abind
  - ape
  - FNN
  - fields
  - ggplot2
  - MASS
  - Matrix
  - MCMCpack
  - nnet
  - pdist
  - pROC
  - statmod
  - truncnorm
  - Hmisc

warnings_are_errors: false

r_check_revdep: false
